# Generated by Django 4.0.3 on 2022-04-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('employee_count', models.IntegerField(default=100)),
                ('domain', models.CharField(max_length=50)),
                ('customer_serving', models.BooleanField(default=True)),
                ('tech_company', models.BooleanField(default=True)),
                ('accepts_user_input', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(default=False)),
                ('di_values', models.IntegerField(default=1)),
                ('acs_values', models.IntegerField(default=1)),
                ('di_resources', models.CharField(max_length=3000)),
                ('acs_resources', models.CharField(max_length=3000)),
                ('dias_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('complaint_type', models.CharField(max_length=20)),
                ('complaint_proof', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dias.company')),
            ],
        ),
    ]
